### ISSUE TITLE
authinfo1 was works

### ISSUE THREAD

**Issue by ivan1986** [DENICeG/go-rriclient#1]
Hey, it was works

https://github.com/DENICeG/go-rriclient/blob/913585f52570c46f6fc1f5af1c03ae6781ce98c1/commandline.go#L133
https://github.com/DENICeG/go-rriclient/blob/913585f52570c46f6fc1f5af1c03ae6781ce98c1/commandline.go#L167

authinfo1 <domain> <code>

**Comment by sbreitf1** [comment]
We're working on it. For now try using the "raw" command and enter the AuthInfo1 query in Key-Value notation:

```
Version: 3.0
Action: CREATE-AUTHINFO1
Domain: de-example.de
AuthInfoHash: 4213d924230224fd719218b4acbd92f96ebe4344f3d5d1478dede1aa44e4cf4b
AuthInfoExpire: 20202809
```
