### ISSUE TITLE
Support for RRI version 4.0

### ISSUE THREAD

**Issue by tillwestpfahl** [DENICeG/go-rriclient#10]
This Client currently only runs on RRI Version 3.0. 

https://github.com/DENICeG/go-rriclient/blob/3dc136d42d7a99185f940557a72fc3ceeafe29ae/pkg/rri/query.go#L16

As members are urged to upgrade, the official repositories should lead the way:

> Please switch your clients to the new RRI protocol version in due time, but no later than by 6 May 2024. After that date, version 3.0 will no longer be supported.

**Comment by sebjung** [comment]
The client has been update to support the latest RRI Version 4.0. Thanks for your hint.

**Comment by tillwestpfahl** [comment]
Nice. When do you plan to release that change?

**Comment by sebjung** [comment]
Ah, good point! I've created a tag, so you should be able to update to the latest version.
