### ISSUE TITLE
Full support for RRI 5.0

### ISSUE THREAD

**Issue by pawel-kow** [DENICeG/go-rriclient#12]
As this change is coming, the client should support 5.0 natively as well.

**Comment by pawel-kow** [comment]
This one does not look like fully fixed. Verification Information is missing in the command output
<img width="943" alt="image" src="https://github.com/user-attachments/assets/fa36d860-c241-42e5-8348-2ec205f65900">

**Comment by Nerzal** [comment]
Fixed in V1.24.0

**Comment by pawel-kow** [comment]
works fine now, thanks!
