### ISSUE TITLE
PutToQueryFields typo

### ISSUE THREAD

**Issue by git-flexi** [DENICeG/go-rriclient#17]
Moin,

In meinem Fork hatte sich leider ein kleiner Fehler in folgender Zeile eingeschlichen:
https://github.com/DENICeG/go-rriclient/blob/74bef1266fa7e8de71618c0bf9366f79b02b6e9e/pkg/rri/verification_information.go#L27

Das sollte natürlich wie folgt aussehen:
`verifiedClaimSlice[i] = string(verificationInformation.VerifiedClaim[i])`

Grüße

**Comment by Nerzal** [comment]
Danke für den Hinweis!
