### ISSUE TITLE
NewVerifyQueueDeleteQuery and NewVerifyQueueReadQuery do not work

### ISSUE THREAD

**Issue by tillwestpfahl** [DENICeG/go-rriclient#7]
They fail with "63000060102 Inadmissible value for keyword "Action"".

It works, if I build the query myself with "QUEUE-READ" and "QUEUE-DELETE" instead of:

```
	ActionVerifyQueueRead QueryAction = "VERIFY-QUEUE-READ"
	ActionVerifyQueueDelete QueryAction = "VERIFY-QUEUE-DELETE"
```

**Comment by sbreitf1** [comment]
The actual QUEUE-READ and QUEUE-DELETE actions are not yet implemented in the Client.

All Verify-related Commands are deprecated and no longer supported by RRI. We forgot to remove the old code from the Client, thanks for pointing that out! In the next version Client implementations for Verify-Actions will be removed and QUEUE-READ and DELETE implementations according to Denic-29 will be added.
